// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore Generated by the OpenNext build before Wrangler bundles this entrypoint.
import openNextWorker from "./.open-next/worker.js";
import { EmailMessage } from "cloudflare:email";
import { createSupabaseMonitoringRepository, runScheduledMonitoring } from "./lib/scheduled-monitoring";

type WorkerEnv = {
  EMAIL: { send(message: EmailMessage): Promise<unknown> };
  NEXT_PUBLIC_SUPABASE_URL: string;
  SUPABASE_SERVICE_ROLE_KEY: string;
};

type ScheduledContext = { waitUntil(promise: Promise<unknown>): void };

const worker = {
  fetch: openNextWorker.fetch,

  async scheduled(_event: unknown, env: WorkerEnv, ctx: ScheduledContext) {
    ctx.waitUntil(runScheduledMonitoring(
      createSupabaseMonitoringRepository(env),
      {
        async send(message) {
          await env.EMAIL.send(new EmailMessage(message.from, message.to, message.raw));
        },
      }
    ));
  },
};

export default worker;
